import fs from 'node:fs'
import { dirname, extname, join, relative } from 'node:path'

export interface MarkdownComponentPlayground {
  entry: string
  files: Record<string, string>
  id: string
  source: string
}

export interface MarkdownComponentPlaygroundOptions {
  contentRoot: string
  generatedRegistryPath: string
  virtualPrefix?: string
}

export interface MarkdownComponentPlaygroundRegistryOptions {
  generatedRegistryPath: string
  virtualPrefix?: string
}

export const DEFAULT_MARKDOWN_COMPONENT_PLAYGROUND_PREFIX = 'virtual:docs-markdown-playground/'

export function walkMarkdownFiles(rootDir: string): string[] {
  if (!fs.existsSync(rootDir)) {
    return []
  }

  const files: string[] = []
  const stack = [rootDir]

  while (stack.length > 0) {
    const current = stack.pop()!
    for (const entry of fs.readdirSync(current)) {
      const fullPath = join(current, entry)
      const info = fs.statSync(fullPath)
      if (info.isDirectory()) {
        stack.push(fullPath)
        continue
      }

      if (extname(fullPath) === '.md') {
        files.push(fullPath)
      }
    }
  }

  return files
}

export function hashPlaygroundSource(source: string): string {
  let hash = 2166136261
  for (let index = 0; index < source.length; index += 1) {
    hash ^= source.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }

  return (hash >>> 0).toString(36)
}

export function parsePlaygroundSourceOptions(source: string): Record<string, string> {
  const options: Record<string, string> = {}
  const firstFileFenceIndex = source.search(/^```/m)
  const header = firstFileFenceIndex >= 0 ? source.slice(0, firstFileFenceIndex) : source

  for (const line of header.split('\n')) {
    const match = line.match(/^([a-zA-Z0-9_-]+):\s*(.+)$/)
    if (match?.[1] && match[2]) {
      options[match[1]] = match[2].trim()
    }
  }

  return options
}

export function parsePlaygroundSourceFiles(source: string): Record<string, string> {
  const files: Record<string, string> = {}
  const fileFenceRe = /^```([a-zA-Z0-9_-]+)\s+file=(\S+)\s*\n([\s\S]*?)\n```/gm
  let match: RegExpExecArray | null

  while ((match = fileFenceRe.exec(source)) !== null) {
    if (match[2] && typeof match[3] === 'string') {
      files[match[2]] = match[3]
    }
  }

  return files
}

export function collectMarkdownComponentPlaygrounds(contentRoot: string): MarkdownComponentPlayground[] {
  const demos = new Map<string, MarkdownComponentPlayground>()
  const playgroundBlockRe = /^````playground-src\s*\n([\s\S]*?)\n````/gm

  for (const filePath of walkMarkdownFiles(contentRoot)) {
    const markdown = fs.readFileSync(filePath, 'utf8')
    let match: RegExpExecArray | null

    while ((match = playgroundBlockRe.exec(markdown)) !== null) {
      const blockSource = match[1]
      if (!blockSource) {
        continue
      }

      const options = parsePlaygroundSourceOptions(blockSource)
      const entry = options.entry
      if (options.mode !== 'component' || !entry?.endsWith('.vue')) {
        continue
      }

      const files = parsePlaygroundSourceFiles(blockSource)
      const source = files[entry]
      if (typeof source !== 'string') {
        throw new Error(
          `[docs] Markdown component playground in ${relative(process.cwd(), filePath)} uses entry "${entry}", but that file was not found in the playground block.`
        )
      }

      const id = hashPlaygroundSource(source)
      demos.set(id, {
        entry,
        files,
        id,
        source
      })
    }
  }

  return [...demos.values()].sort((left, right) => left.id.localeCompare(right.id))
}

function toMarkdownImportVarName(demoId: string): string {
  return `MarkdownPlayground${demoId.replace(/[^a-zA-Z0-9_$]/g, '_')}Demo`
}

export function writeMarkdownComponentPlaygroundRegistry(
  demos: MarkdownComponentPlayground[],
  options: MarkdownComponentPlaygroundRegistryOptions
): void {
  const virtualPrefix = options.virtualPrefix ?? DEFAULT_MARKDOWN_COMPONENT_PLAYGROUND_PREFIX
  const lines: string[] = []
  lines.push('// This file is auto-generated by vue-ssg markdown playground scanner. Do not edit manually.')
  lines.push("import type { Component } from 'vue'")
  lines.push('')

  for (const demo of demos) {
    lines.push(`import ${toMarkdownImportVarName(demo.id)} from '${virtualPrefix}${demo.id}.vue'`)
  }

  lines.push('')
  lines.push('export const docsVirtualPlaygroundRegistry: Record<string, Component> = {')
  for (const demo of demos) {
    lines.push(`  '${demo.id}': ${toMarkdownImportVarName(demo.id)},`)
  }
  lines.push('}')
  lines.push('')
  lines.push('export const docsVirtualPlaygroundSourceRegistry: Record<string, string> = {')
  for (const demo of demos) {
    lines.push(`  '${demo.id}': ${JSON.stringify(demo.source)},`)
  }
  lines.push('}')
  lines.push('')
  lines.push("export const docsVirtualPlaygroundSourceFileRegistry: Record<string, string> = {")
  for (const demo of demos) {
    lines.push(`  '${demo.id}': ${JSON.stringify(demo.entry)},`)
  }
  lines.push('}')
  lines.push('')
  lines.push("export const docsVirtualPlaygroundSourceLanguageRegistry: Record<string, string> = {")
  for (const demo of demos) {
    lines.push(`  '${demo.id}': 'vue',`)
  }
  lines.push('}')
  lines.push('')

  fs.mkdirSync(dirname(options.generatedRegistryPath), { recursive: true })
  fs.writeFileSync(options.generatedRegistryPath, lines.join('\n'), 'utf8')
}

export function createMarkdownComponentPlaygroundPlugin(
  demos: MarkdownComponentPlayground[],
  virtualPrefix = DEFAULT_MARKDOWN_COMPONENT_PLAYGROUND_PREFIX
) {
  const sourceById = new Map(demos.map((demo) => [demo.id, demo.source]))

  return {
    name: 'vue-ssg-markdown-component-playgrounds',
    resolveId(id: string) {
      if (id.startsWith(virtualPrefix)) {
        return id
      }

      return null
    },
    load(id: string) {
      if (!id.startsWith(virtualPrefix)) {
        return null
      }

      const demoId = id
        .slice(virtualPrefix.length)
        .replace(/\.vue$/, '')

      return sourceById.get(demoId) ?? null
    }
  }
}

export function createMarkdownComponentPlaygrounds(options: MarkdownComponentPlaygroundOptions) {
  const virtualPrefix = options.virtualPrefix ?? DEFAULT_MARKDOWN_COMPONENT_PLAYGROUND_PREFIX
  const demos = collectMarkdownComponentPlaygrounds(options.contentRoot)

  writeMarkdownComponentPlaygroundRegistry(demos, {
    generatedRegistryPath: options.generatedRegistryPath,
    virtualPrefix
  })

  return {
    demos,
    plugin: createMarkdownComponentPlaygroundPlugin(demos, virtualPrefix),
    virtualPrefix
  }
}
