export {
  defineDocsConfig,
  type DocsAsideProps,
  type DocsBrandProps,
  type DocsComponentsConfig,
  type DocsConfig,
  type DocsFooterConfig,
  type DocsFooterProps,
  type DocsHeaderNavConfig,
  type DocsHeaderNavProps,
  type DocsHeaderProps,
  type DocsHomeActionConfig,
  type DocsHomeConfig,
  type DocsLayoutConfig,
  type DocsLayoutProps,
  type DocsLayoutVariant,
  type DocsPageMeta,
  type DocsSectionConfig,
  type DocsSidebarProps,
  type DocsSiteConfig,
  type DocsSiteLogoConfig,
  type DocsTocConfig
} from '@codemonster-ru/vue-ssg-core'
