// This file is auto-generated by vue-ssg markdown playground scanner. Do not edit manually.
import type { Component } from 'vue'

import MarkdownPlayground28879fDemo from 'virtual:docs-markdown-playground/28879f.vue'

export const docsVirtualPlaygroundRegistry: Record<string, Component> = {
  '28879f': MarkdownPlayground28879fDemo,
}

export const docsVirtualPlaygroundSourceRegistry: Record<string, string> = {
  '28879f': "<template>\n  <main class=\"demo\">\n    <VfCard outlined>\n      <h2>Vue runtime smoke</h2>\n      <p>Bundled by Vite, rendered without iframe runtime.</p>\n      <VfBadge outlined>vueforge-core</VfBadge>\n      <VfButton color=\"accent\">Smoke passed</VfButton>\n    </VfCard>\n  </main>\n</template>\n\n<script setup>\nimport { VfBadge, VfButton, VfCard } from '@codemonster-ru/vueforge-core'\n</script>\n\n<style scoped>\n.demo {\n  padding: var(--vf-layout-space-layout-lg);\n  display: grid;\n  align-content: start;\n  gap: var(--vf-layout-space-layout-base);\n  background: linear-gradient(\n    180deg,\n    color-mix(in oklab, var(--vf-color-bg) 92%, var(--vf-color-brand-primary) 8%),\n    var(--vf-color-bg)\n  );\n}\n\nh2 {\n  margin: 0 0 12px;\n  font-size: 42px;\n  line-height: 1.1;\n}\n\np {\n  margin: 0 0 20px;\n}\n\n.vf-button {\n  width: 100%;\n  justify-content: center;\n  margin-top: 20px;\n}\n</style>",
}

export const docsVirtualPlaygroundSourceFileRegistry: Record<string, string> = {
  '28879f': "/App.vue",
}

export const docsVirtualPlaygroundSourceLanguageRegistry: Record<string, string> = {
  '28879f': 'vue',
}
